name: Lint ROS2 package

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ "*"]

env:
  PACKAGE_NAME: "adi_iio"

jobs:
  ament_lint:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          # Humble Hawksbill (May 2022 - May 2027) - Ubuntu 22.04 (Jammy)
          - humble
        linter:
          - cppcheck
          - uncrustify
          - pep257
          - lint_cmake
          - xmllint
          # - cpplint # TBD
          # - flake8 # TBD

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
          use-ros2-testing: false

      - name: Run Linter
        env:
          AMENT_CPPCHECK_ALLOW_SLOW_VERSIONS: 1
        uses: ros-tooling/action-ros-lint@master
        with:
          linter: ${{ matrix.linter }}
          distribution: ${{ matrix.ros_distribution }}
          package-name: ${{ env.PACKAGE_NAME }}

  pre_commit:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          # Humble Hawksbill (May 2022 - May 2027) - Ubuntu 22.04 (Jammy)
          - humble

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install pip packages
        working-directory: ${{ github.workspace }}
        run: |
          pip install pip --upgrade
          pip install -r requirements.txt

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
          use-ros2-testing: false

      - name: Run pre-commit-checks
        working-directory: ${{ github.workspace }}
        run: |
          . /opt/ros/${{ matrix.ros_distribution }}/setup.sh
          make fix
          FIX_STATUS=$?

          make check
          CHECK_STATUS=$?

          if [ $FIX_STATUS -ne 0 ] || [ $CHECK_STATUS -ne 0 ]; then
            echo "Pre-commit checks failed. Please fix the issues and try again."
            exit 1
          fi
